// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ezuujivxstyuziclhvhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dXVqaXZ4c3R5dXppY2xodmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzE5MjYsImV4cCI6MjA2Mjg0NzkyNn0.4aD22PEkf8Hid5fMm_leOOj55z-enRitR5IusZq3Uww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);